# Generated by Django 6.0.3 on 2026-03-09 13:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location_name', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('zone', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('installed_date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DetectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_type', models.CharField(choices=[('elephant', 'Elephant'), ('tiger', 'Tiger'), ('leopard', 'Leopard'), ('bear', 'Bear'), ('wild_boar', 'Wild Boar'), ('deer', 'Deer'), ('unknown', 'Unknown')], max_length=50)),
                ('confidence', models.FloatField(default=0.0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='detections/')),
                ('annotated_image', models.ImageField(blank=True, null=True, upload_to='annotated/')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('gps_lat', models.FloatField()),
                ('gps_lng', models.FloatField()),
                ('location_name', models.CharField(default='Forest Border', max_length=200)),
                ('status', models.CharField(choices=[('detected', 'Detected'), ('verified', 'Verified'), ('false_alarm', 'False Alarm'), ('action_taken', 'Action Taken')], default='detected', max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.camera')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AlertMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_to', models.CharField(max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('message_body', models.TextField()),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivery_status', models.CharField(default='simulated', max_length=20)),
                ('detection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.detectionlog')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='ForestOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('zone', models.CharField(max_length=50)),
                ('designation', models.CharField(default='Forest Guard', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
